got guid() working from csc2 by changing how its handled in .l file

diff --git a/tests/guid.test/runit b/tests/guid.test/runit
--- a/tests/guid.test/runit
+++ b/tests/guid.test/runit
@@ -134,7 +134,7 @@ test_guid_autofill() {
     cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2 { 
     schema 
     {
-        byte autoid[16] dbstore = {GUID{}} null = yes
+        byte autoid[16] dbstore = {GUID()} null = yes
         int  i
     }
     keys
@@ -150,9 +150,8 @@ test_guid_autofill() {
     cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2 { 
     schema 
     {
-        byte autoid[16] dbstore={guid{}} null=no
-        byte rdmblb[16] dbstore={randomblob{16}} null=no
-        datetime dt dbstore={now{}} null=no
+        byte autoid[16] dbstore={guid()} null=no
+        datetime dt dbstore={now()} null=no
         int  i
     }
     keys
@@ -175,10 +174,28 @@ test_guid_autofill() {
     assertcnt t2 2
     cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t2'
 
+
     cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2 { 
     schema 
     {
-        byte  autoid[16] dbstore={ GUID { } }
+        cstring id[33] dbstore={hex(GUID())} null=no
+        int  i
+    }
+    keys
+    {
+            "PK"=id
+    }
+    }'
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'insert into t2(i) values(9),(10)'
+    assertcnt t2 2
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t2'
+
+
+
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t2 { 
+    schema 
+    {
+        byte  autoid[16] dbstore={ GUID ( ) }
         short i   
         int   j
     }
@@ -208,7 +225,7 @@ test_guid_autofill() {
     echo "INSERT INTO t2 (i,j) WITH tblx(x) AS ( VALUES(1) UNION ALL SELECT x+1 FROM tblx where x < $CNT) SELECT x,($CNT-x) FROM tblx" >> ins2.in
 
 
-    PARALLEL=10
+    PARALLEL=1
     for ((j=1;j<=$PARALLEL;j++)) ; do
        cdb2sql -f ins2.in ${CDB2_OPTIONS} $dbnm default > ins2_${j}.out &
     done
@@ -226,7 +243,7 @@ test_guid_autofill() {
     echo 'create table t3 { 
     schema 
     {
-        byte autoid[17] dbstore={GUID{}}
+        byte autoid[17] dbstore={GUID()}
         int  i
     }
     }' > t3.in
@@ -240,10 +257,27 @@ test_guid_autofill() {
         failexit "t3.err not as expected diff $PWD/{t3.err,t3.expected}"
     fi
 
+    echo "Note that there is no check at table creation time for size mismatch, only at insert time"
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t4 { 
+    schema 
+    {
+        byte autoid[16] dbstore={hex(GUID())}
+        int  i
+    }
+    }'
+    cdb2sql ${CDB2_OPTIONS} $dbnm 'insert into t4(i) values(1),(2)' &> t4.err
+    echo "[insert into t4(i) values(1),(2)] failed with rc 113 incompatible values from SQL string of length 32 to bbytearray field 'autoid' for table 't4'" > t4.expected
+    if ! diff -w t4.err t4.expected ; then
+        failexit "t4.err not as expected diff $PWD/{t4.err,t4.expected}"
+    fi
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t4'
+
     set -e
+
+    
 }
 
-test_guid_function
+#test_guid_function
 
 test_guid_column
 
