trying to pass string parameters to functions for dbstore

diff --git a/tests/guid.test/runit b/tests/guid.test/runit
--- a/tests/guid.test/runit
+++ b/tests/guid.test/runit
@@ -134,8 +134,10 @@ test_guid_autofill() {
     cdb2sql ${CDB2_OPTIONS} $dbnm default "create table t2 { 
     schema 
     {
-        byte autoid[16] dbstore = {GUID()} null = yes
-        byte bytfld[4] dbstore = x'00112233' null = yes
+        byte autoid[16] dbstore = {GUID()} null = no
+        byte bytfld1[16] dbstore = {randomblob(16)} null = yes
+        byte bytfld2[4] dbstore = x'00112233' null = yes
+        byte bytfld2[4] dbstore = {hex('hi')} null = yes
         int  i
     }
     keys
@@ -152,7 +154,8 @@ test_guid_autofill() {
     schema 
     {
         byte autoid[16] dbstore={guid()} null=no
-        datetime dt dbstore={now()} null=no
+        datetime dt     dbstore={current_timestamp} null=no
+        datetime dtnow  dbstore={now()} null=no
         int  i
     }
     keys
@@ -226,7 +229,7 @@ test_guid_autofill() {
     echo "INSERT INTO t2 (i,j) WITH tblx(x) AS ( VALUES(1) UNION ALL SELECT x+1 FROM tblx where x < $CNT) SELECT x,($CNT-x) FROM tblx" >> ins2.in
 
 
-    PARALLEL=10
+    PARALLEL=1
     for ((j=1;j<=$PARALLEL;j++)) ; do
        cdb2sql -f ins2.in ${CDB2_OPTIONS} $dbnm default > ins2_${j}.out &
     done
@@ -261,32 +264,32 @@ test_guid_errors() {
         failexit "t3.err not as expected diff $PWD/{t3.err,t3.expected}"
     fi
 
-#    echo "Note that there is no check at table creation time for size mismatch, only at insert time"
-#    cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t4 { 
-#    schema 
-#    {
-#        byte autoid[16] dbstore={hex(GUID())}
-##        int  i
-#    }
-#    }'
-#    sleep 1
-#    cdb2sql ${CDB2_OPTIONS} $dbnm 'insert into t4(i) values(1),(2)' &> t4.err
-#    echo "[insert into t4(i) values(1),(2)] failed with rc 113 incompatible values from SQL string of length 32 to bbytearray field 'autoid' for table 't4'" > t4.expected
-#    if ! diff -w t4.err t4.expected ; then
-#        failexit "t4.err not as expected diff $PWD/{t4.err,t4.expected}"
-#    fi
-#    cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t4'
+    echo "Note that there is no check at table creation time for size mismatch, only at insert time"
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'create table t4 { 
+    schema 
+    {
+        byte autoid[16] dbstore={hex(GUID())}
+        int  i
+    }
+    }'
+    sleep 1
+    cdb2sql ${CDB2_OPTIONS} $dbnm 'insert into t4(i) values(1),(2)' &> t4.err
+    echo "[insert into t4(i) values(1),(2)] failed with rc 113 incompatible values from SQL string of length 32 to bbytearray field 'autoid' for table 't4'" > t4.expected
+    if ! diff -w t4.err t4.expected ; then
+        failexit "t4.err not as expected diff $PWD/{t4.err,t4.expected}"
+    fi
+    cdb2sql ${CDB2_OPTIONS} $dbnm default 'drop table t4'
 
     set -e
 
     
 }
 
-test_guid_function
+#test_guid_function
 
-test_guid_column
+#test_guid_column
 
-test_guid_autofill
+#test_guid_autofill
 
 test_guid_errors
 
